sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

env:
  - STACK_YAML=stack.yaml

install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz | tar -xvz
  - mv stack-1.1.2-linux-x86_64/stack ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - stack --version
  - stack setup

script:
  - stack test
